// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoigGPT-6DcndV8J_JhoKmRKh7sDJJ6J0', // Using your Android key temporarily
    appId: '1:1088466638917:web:YOUR_WEB_APP_ID', // You need to get this from Firebase Console
    messagingSenderId: '1088466638917',
    projectId: 'instarecipe-eb125',
    authDomain: 'instarecipe-eb125.firebaseapp.com',
    storageBucket: 'instarecipe-eb125.appspot.com',
    measurementId: 'G-XXXXXXXXXX', // Optional for now
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoigGPT-6DcndV8J_JhoKmRKh7sDJJ6J0', // From google-services.json
    appId: '1:1088466638917:android:f0aa2fecf2591c86092b2c', // Updated to match Firebase Console
    messagingSenderId: '1088466638917',
    projectId: 'instarecipe-eb125', // From your Firebase Console URL
    storageBucket: 'instarecipe-eb125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '1088466638917',
    projectId: 'instarecipe-eb125',
    storageBucket: 'instarecipe-eb125.appspot.com',
    iosBundleId: 'com.iba.instarecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: '1088466638917',
    projectId: 'instarecipe-eb125',
    storageBucket: 'instarecipe-eb125.appspot.com',
    iosBundleId: 'com.iba.instarecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: '1088466638917',
    projectId: 'instarecipe-eb125',
    authDomain: 'instarecipe-eb125.firebaseapp.com',
    storageBucket: 'instarecipe-eb125.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );
} 